name: CI
on:
  pull_request:
  push: { branches: [main, develop] }
  schedule: [cron: 0 0 * * 1]
  workflow_dispatch:
  workflow_call:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cloud-processor:
    uses: ./.github/workflows/python-build.yml
    with: { directory: cloud-processor }
  edge-client:
    uses: ./.github/workflows/python-build.yml
    with: { directory: edge-client }
  voice-agent:
    uses: ./.github/workflows/python-build.yml
    with: { directory: voice-agent }